services:
  postgres:
    build:
      context: docker
      dockerfile: postgres/postgres.dockerfile
    environment:
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB}:5432
    networks:
      - notification_telegram
volumes:
  postgres_data:
networks:
  notification_telegram:
    driver: bridge