package ru.sergalas.notification.enums;

public enum CallbackEnum {
   MAIN,
   NOTIFICATION_MAIN,
   NOTIFICATION_NEW,
   NOTIFICATION_EDIT_TITLE_,
   NOTIFICATION_EDIT_DESC_,
   NOTIFICATION_EDIT_TIME_,
   NOTIFICATION_DONE_,
   NOTIFICATION_BACK_;
}

